### PR TITLE
Remove yoda conditions

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by greg0ire** [comment]
@Soullivaneuh , can you review this ?

**Comment by Soullivaneuh** [comment]
The code looks good, nice catch for the `is_callable`!

But I have to tell again, this should not be done in the name for the yoda condition removal.

Follow a convention with a bench of "exceptions" only because you don't like them is a very bad idea. :wink:

**Comment by greg0ire** [comment]
Then I guess I'll just drop the convention to PSR2

**Comment by Soullivaneuh** [comment]
You have lot of symfony integration. It would be better to keep it, but it's your project! :wink: 

Maybe the Laravel convention will better feet your needs?

**Comment by greg0ire** [comment]
> You have lot of symfony integration. It would be better to keep it, but it's your project! :wink: 

I'd rather be hazy about what the conventions are than force everyone to use Yoda conditions / oneline method signatures.

**Comment by Soullivaneuh** [comment]
> than force everyone to use Yoda conditions / oneline method signatures.

We can say the same for short array syntax, space between operator etc etc... this is why conventions exists.

**Pull request merged**
