### PR TITLE
Add PHP 7 support

### PR DESCRIPTION
**Pull request by Soullivaneuh**

### CODE REVIEW

**Comment by greg0ire** [comment]
You can move the nightly build to `allowed_failures` if you want to :)

**Comment by greg0ire** [comment]
Not sure this will be useful very long : https://wiki.php.net/rfc/enum

But it doesn't hurt.

**Comment by Soullivaneuh** [comment]
@greg0ire done.

**Comment by greg0ire** [comment]
Thanks!

**Pull request merged**
